### PR TITLE
Minor - Adds autoBestAlign attribute.

### PR DESCRIPTION
**Pull request by fernandosouza**

### CODE REVIEW

**Comment by fernandosouza** [comment]
cc. @ygorcosta

**Comment by jbalsas** [comment]
Hey @fernando, did you run 'gulp format' for that last commit?

I'm not sure if we had finally settled on using that, since it wasn't producing exactly the output we wanted... what do you think @eduardolundgren?

**Comment by fernandosouza** [comment]
Yes, @jbalsas. I did.

**Comment by jbalsas** [comment]
I think Eduardo was looking into eslint for
this... I'd lean towards clang-formatter (google) or prettier, but I think
it's time we settle on something :)

**Comment by fernandosouza** [comment]
So. Should I drop this commit, then?

**Comment by jbalsas** [comment]
It's fine either way, but yeah, I'd wait until we settle on something final to avoid moving it around (that's what we did in other cases iirc).

I don't fully understand the assertion in the tests. Could you clarify what it is doing?

I'm on the phone, so not very reliable, but other than that, looks good to me. :)

**Comment by eduardolundgren** [comment]
LGTM.

**Comment by eduardolundgren** [comment]
@jbalsas For style guide we should enforce https://github.com/google/eslint-config-google as example here https://github.com/wedeploy/magnet/blob/master/.eslintrc. For automatic formatting we need to make a decision. Maybe we can try prettier and see how it behaves with the google eslint rules, if the are compatible it might be okay. Could you guys give a try?

**Comment by fernandosouza** [comment]
@jbalsas, both tests only guarantee that the value of the `autoBestAlign` attribute is being sent to the `Align.align` method.

The `metal-position` component is the one responsible for aligning the list of elements. That's why it's not necessary to check if the list were aligned correctly in those tests, only if the component in charge of that receives the right information.

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Thanks @fernandosouza, I checked on the phone and didn't have the whole context, so I didn't see that we were stubbing `Align.align`. Makes sense now :)

I'll remove the format commit since we're close to reach an agreement and merge and publish this.

Thanks!

**Comment by jbalsas** [comment]
Merged and published! 🎉

**Pull request closed without merging**
